### ISSUE TITLE
閏年の課題についての悩みごとはありますか？

### ISSUE THREAD

**Issue by wakita** [titech-is-cs115/lx02#1]

**Comment by 3tty0n** [comment]
演習室のキーボードが使えず自分のMacで作業してるのですが

```
> run
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 0 s, completed 2015/10/13 15:45:56
>

```

となって辛いです
どうしたらいいでしょう

`>test`したら恒常的に

```
> test
[success] Total time: 0 s, completed 2015/10/13 15:45:54

```

となり厳しいです

**Comment by 3tty0n** [comment]
`build.sbt`に`fork in run := true`を書くことで解決しました

**Comment by wakita** [comment]
サポートしたいのですが、事情がよく見えません。おっしゃるように main 関数が定義されていないと `run` コマンドは利用できません。ですので、`run` コマンドがエラーになるのは正常です。

`test` については、よくわかりません。`fork in run` は実行時の Java の仮想機械の複製にかかわる設定なので、`test` の問題とは無関係のはずなんですが。

**Comment by 3tty0n** [comment]
`src`フォルダ内で`sbt`を実行したら上のようになったので、その直上のフォルダ（`build.sbt`が置いてあるところ）で`sbt`を起動したら問題なく`> test`が実行できました
なのでこれは自分が`sbt`を起動した場所が悪かったのだと解釈しました
お手数おかけして申し訳ありません

**Comment by wakita** [comment]
なるほど。そういうことはありますね。問題が解決したので、この issue は閉じますね。
